Option 1: Basic executor interface
louisaberger/procexec pull request #2
Opened 2019-02-19 20:38 UTC by louisaberger

2019-02-22 16:49 UTC, tolsen requested changes

2019-02-22 16:49 UTC, tolsen commented on executor.go
> +	Execute(map[string]interface{}, chan *GoroutinePanic) error
Do we really need map[string]interface{} ?  Couldn't the Executor just be configured through the struct that implements it?

Also, Execute() should take a goctx

2019-02-22 16:49 UTC, tolsen commented on main/executor_poc.go
> +		case <-stopChan:
if we add goctx to Execute() then we can add a case statement that listens for goctx.Done() (which is a channel).

I'm thinking goctx can be used for immediate cancellation.  Whereas Stop() can be used for asking more nicely for things to be stopped.  Stop() could also have discretion to use a subcontext of the goctx passed in for cancelling things.

2019-02-22 16:49 UTC, tolsen commented on executor.go
> +	// Stop should only be called once by the caller.
I'm wondering if we should instead allow Stop() to be called multiple times and it's the Executor's responsibility to handle that.  This allows you to mix defer Stop() with explicit calls to Stop() in the same section of code.

2019-02-22 19:59 UTC, louisaberger commented on executor.go
> +	Execute(map[string]interface{}, chan *GoroutinePanic) error
Would the implementation need to actually do anything with goctx? Or does it just allow us to cancel the call from the caller? 

The map[string]interface{} is the equivalent of the "Backup/Monitoring" config file we previously had, so we do need to pass in the explicit config that we want to execute. Does that make sense to you? Can add an extra note into the comment explaining that

2019-02-22 20:11 UTC, tolsen commented on executor.go
> +	Execute(map[string]interface{}, chan *GoroutinePanic) error
Then that's making it specific to Backup/Monitoring.  Why not just have a map[string]interface{} in the struct that implements the interface?

As for goctx, yes, it should pass it wherever a goctx is needed.  Also, goctx->Done() should be listened to in the main select statement.

Also, I was thinking we could have PanicCapturingGo take in a goctx and the function that is passed to it also take in a goctx.  Then PanicCapturingGo could pass a sub context of goctx to the function.  Then if there's a panic, it can call the cancel function.

2019-02-22 21:39 UTC, louisaberger commented on executor.go
> +	Execute(map[string]interface{}, chan *GoroutinePanic) error
The config specification can change though -- how would the caller (Automation in this case) specify what new config to Execute with? 

I'd like to get more specific in the instructions to the implementor about "wherever a goctx is needed" -- could you be more specific? 

And by "main select statement" here, do you mean the "RunAgent" function in my poc example? I think you're saying that we would still keep a "Stop()" function that politely waits for the progressGroup to complete, but passing a goctx in means that we could call cancel on the goctx, and all the goroutines spawned from the Execute() function would be terminated?

Will think on the third point, but might ask you for an example of that.

2019-02-22 21:42 UTC, tolsen commented on executor.go
> +	Execute(map[string]interface{}, chan *GoroutinePanic) error
Oh.  I was thinking it would just construct a new struct when the config changed.

Contexts are passed anywhere there is I/O.  Specifically when you execute commands or network calls.

Yes, the RunAgent function.

2019-02-22 21:44 UTC, louisaberger commented on executor.go
> +	// Stop should only be called once by the caller.
I originally felt the same way, but the idea here was that this allows the implementation to control how much it cares about stopping things, and for the caller to be in charge of deciding when to abandon the effort (which also means that the caller just implements this once, and the implementations do not have to)

Not quite sure I see why you would have a defer Stop() and later Stops() -- could you explain that?

2019-02-22 22:04 UTC, louisaberger commented on executor.go
> +	Execute(map[string]interface{}, chan *GoroutinePanic) error
(sorry, edited my previous comment after your response by accident :) could you revisit my "main select statement" question?)

2019-02-22 22:13 UTC, tolsen commented on executor.go
> +	// Stop should only be called once by the caller.
Here's an example with cancelFunc(): https://github.com/10gen/mms-automation/blob/CLOUDP-33451/go_planner/src/com.tengen/cm/mongoclientservice/mongoclientservice.go#L603-L632

2019-02-22 22:14 UTC, tolsen commented on executor.go
> +	// Stop should only be called once by the caller.
On other words, sometimes you want to add a defer to make sure it gets called.  And then sometimes you want to call it sooner than when the defer is going to happen.  So you end up calling it twice because the defer still happens.

2019-02-25 18:58 UTC, louisaberger commented on main/executor_poc.go
> +		case <-stopChan:
1. So are you imagining that the caller would have a "WaitForStop" function that waits for Stop() to return, but cancels via the goctx if the nice Stop() call times out? 

2. Would this also mean that all the spawned goroutines out of RunAgent that listen for Stop() would also need to listen for goctx.Done()? Or does goctx know to return from teh function immediately, without having to listen to goctx.Done()?

2019-02-25 18:58 UTC, louisaberger commented on executor.go
> +	Execute(map[string]interface{}, chan *GoroutinePanic) error
Do you have an opinion of constructing a new struct vs reusing the same one? I don't have a particular feeling either way, open to suggestions

2019-02-25 19:24 UTC, tolsen commented on main/executor_poc.go
> +		case <-stopChan:
1. That would work

2. Any I/O or command execution function (such as an HTTP call, Go driver call, or exec.Command call) that takes a goctx should return immediately with an error if the context is cancelled.  If a goroutine is doing something else that can take a while (such as something CPU intensive, then it will have to listen for goctx.Done()or check goctx.Err() occasionally )

2019-02-25 19:25 UTC, tolsen commented on executor.go
> +	Execute(map[string]interface{}, chan *GoroutinePanic) error
Construct a new struct.  Then we can remove the map and it becomes more general purpose.

2019-02-25 20:04 UTC, louisaberger commented on executor.go
> +	Execute(map[string]interface{}, chan *GoroutinePanic) error
Done, pushed new struct change.

2019-02-25 21:56 UTC, tolsen requested changes

2019-02-25 21:56 UTC, tolsen commented on concurrency.go
> +func PanicCapturingGo(f func(), panicChan chan *GoroutinePanic, processWG *sync.WaitGroup) {
may want to pass a cancelFunc here if we'd like to call it upon catching the panic.  Not sure about this though

2019-02-25 21:56 UTC, tolsen commented on main/executor_poc.go
> +	cancelFuncLock sync.Mutex
Do we need the cancelFuncLock?  I would assume cancelFuncs are immutable?  And I think any individual cancelFunc is threadsafe to call.

2019-02-25 21:59 UTC, louisaberger commented on main/executor_poc.go
> +	cancelFuncLock sync.Mutex
Probably not! Copied it over from our Director implementation, but it looks like it's safe to call https://golang.org/pkg/context/#CancelFunc

2019-02-25 22:28 UTC, louisaberger commented on concurrency.go
> +func PanicCapturingGo(f func(), panicChan chan *GoroutinePanic, processWG *sync.WaitGroup) {
So would this mean we'd add a new "ctx" field into the `f` func? So if it panics, we'd call the cancelFunc, and if the "ctx" passed into `f` has been passed to anything it calls, those would cancel?

2019-02-26 02:30 UTC, tolsen commented on concurrency.go
> +func PanicCapturingGo(f func(), panicChan chan *GoroutinePanic, processWG *sync.WaitGroup) {
yep

2019-02-26 15:06 UTC, louisaberger commented
@tolsen Added a context to PanicCapturingGo. Ready for a re-review

2019-02-26 15:07 UTC, louisaberger commented on executor.go
> +	// Stop should only be called once by the caller.
Stop should now be able to be called multiple times (using contexts instead of stopChans)

2019-02-26 16:20 UTC, tolsen approved these changes

2019-02-26 16:52 UTC, merged